# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8968809da298dc0a0c1497be57e896e198467a8f7fd0d6441ccc3da90062ab24f31ac31f86c3adbd473dc7bf0ad248a4ec3f68e78917195c756d9bea4bbac829

test:
  secret_key_base: b0a8d718bf2c945b4d9ac2ae7932cfc8e337280725ee41cef6f460bad3c41272e4337c88436e945d89c9d10865b0477b02d7672b977a5d922fc8beb90baf0cd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
